

eureka:
  instance:
    hostname: localhost
    appname: eureka-peer
  dashboard:
    path: /dashboard
  client:
    register-with-eureka: true #由于该应用为注册中心，所以设置为false, 代表不向注册中心注册自己。
    fetch-registry: true #由于注册中心的职责就是维护服务实例，它并不需要去检索服务， 所以也设置为false。
    service-url:
      defaultZone: http://peer1.eureka.scac:1111/eureka/,http://peer2.eureka.scac:1112/eureka/,http://peer3.eureka.scac:1113/eureka/
---
spring:
  profiles: peer1
server:
  port: 1111
eureka:
  instance:
    hostname: peer1.eureka.scac


---
spring:
  profiles: peer2
server:
  port: 1112
eureka:
  instance:
    hostname: peer2.eureka.scac

---
spring:
  profiles: peer3
server:
  port: 1113
eureka:
  instance:
    hostname: peer3.eureka.scac